In [1]:
# 5. Finding Insertion Index in Sorted Data:import bisect
# Task: Given a sorted price list [10, 20, 30, 50], find the position to insert a new price 25.

import bisect
prices = [10, 20, 30, 50]
position = bisect.bisect(prices, 25)
print(position)



2


In [3]:
# 6. Filtering High Temperatures:
# Task: Identify days with temperatures above 35°C from [30, 36, 40, 28, 37].

temperatures = [30, 36, 40, 28, 37]
high_temperatures = [temp for temp in temperatures if temp > 35]
print(high_temperatures)


[36, 40, 37]


In [5]:
# 7. Extracting High Salary Employees:
# Task: Extract salaries above ₹50,000 from [40000, 55000, 62000, 48000].

salaries = [40000, 55000, 62000, 48000]
high_salaries = [salary for salary in salaries if salary > 50000]
print(high_salaries)




[55000, 62000]


In [7]:
# 8.Generate a 5×5 NumPy array with values from 1 to 25.

import numpy as np
array = np.arange(1, 26).reshape(5, 5)
print(array)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
